[package]
name = "hotshot-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Espresso Systems <hello@espressosys.com>"]
license = "MIT"
rust-version = "1.64.0"
homepage = "https://github.com/EspressoSystems/hotshot-primitives"
repository = "https://github.com/EspressoSystems/hotshot-primitives"

[dependencies]
anyhow = "1.0"
ark-bls12-381 = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.4.0"
ark-poly = "0.4.0"
ark-serialize = "0.4.0"
ark-std = { version = "0.4.0", default-features = false }
derivative = "2.2.0"
digest = { version = "0.10" }
jf-primitives = { git = "https://github.com/espressosystems/jellyfish" } # , tag = "0.3.0"
jf-utils = { git = "https://github.com/espressosystems/jellyfish" } # , tag = "0.3.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
sha2 = { version = "0.10" }

[features]
default = ["parallel"]
std = ["ark-std/std"]
parallel = ["jf-primitives/parallel"]
