[package]
name = "hotshot-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Espresso Systems <hello@espressosys.com>"]
license = "MIT"
rust-version = "1.64.0"
homepage = "https://github.com/EspressoSystems/hotshot-primitives"
repository = "https://github.com/EspressoSystems/hotshot-primitives"

[dependencies]
ark-std = { version = "0.4.0", default-features = false }
jf-primitives = { git = "https://github.com/espressosystems/jellyfish", tag = "0.3.0" }
jf-utils = { git = "https://github.com/espressosystems/jellyfish", tag = "0.3.0" }
serde = { version = "1.0", default-features = false, features = ["derive", "rc"] }
ark-serialize = "0.4.0"
sha3 = "0.10.7"
tagged-base64 = { git = "https://github.com/espressosystems/tagged-base64", tag = "0.3.0" }
ark-ff = "0.4.0"
ark-bn254 = "0.4.0"

[features]
default = ["parallel"]
std = ["ark-std/std"]
parallel = ["jf-primitives/parallel"]
