[package]
name = "hotshot-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Espresso Systems <hello@espressosys.com>"]
license = "MIT"
rust-version = "1.64.0"
homepage = "https://github.com/EspressoSystems/hotshot-primitives"
repository = "https://github.com/EspressoSystems/hotshot-primitives"

[dependencies]
ark-serialize = "0.4.0"
ark-std = { version = "0.4.0", default-features = false }
bitvec = { version = "1.0.1", features = ["alloc", "atomic", "serde"] }
ethereum-types = { version = "0.14.1", features = ["impl-serde"] }
jf-primitives = { git = "https://github.com/espressosystems/jellyfish", branch = "refactor-bls" }
jf-utils = { git = "https://github.com/espressosystems/jellyfish", rev = "41e9b16b6ed0de5e685ed83225bddf6e2c0a0dba" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
[features]
default = ["parallel"]
std = ["ark-std/std"]
parallel = ["jf-primitives/parallel"]
